query {
  getSettings {
    paymentConfiguration {
      requiresAuthenticationForPreAuthorizedPaymentOption,
    },
    minimumQuantityAccumulatedForItems,
    decimalDigitsPrecision,
    minimumValueAccumulated,
    taxConfiguration {
      url,
      authorizationHeader,
      allowExecutionAfterErrors,
      integratedAuthentication,
    }
  }
}
